### ISSUE TITLE
[Bug]: 多QQ同时运行一段时间后出现的配置文件数据格式错误问题。

### ISSUE THREAD

**Issue by sunaowei** [adproqwq/LiteLoaderQQNT-AutoSendMessages#12]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-AutoSendMessages/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.12-25493

### LiteLoaderQQNT 版本

1.1.2

### 本插件 版本

1.6.0

### 插件检测更新API插件 版本

1.6.2

### Euphony插件 版本

1.1.1

### 运行环境

Windows

### 重现步骤

同一个电脑上运行三个QQ，同时开启该插件，且运行时间间隔均设置为1min。在运行一段时间后，config.json会出现格式不正确的情况，即打开config.json会发现最后一行会出现两个}}，导致后续读取该配置文件均出现错误。

出现错误的频率不定，通常在运行数个小时后会出现。

### 期望的结果是什么？

期望作者修复该问题。

### 实际的结果是什么？

无

**Comment by adproqwq** [comment]
多个QQ同时运行会带来一些不可预料的问题。
配置文件的读写完全由框架提供的API完成，我不清楚为什么会导致这样的问题。
或许你应该到框架的仓库提一个issue。
