### ISSUE TITLE
[Feat]: 使用时间戳记录方式改善qq休眠导致的问题

### ISSUE THREAD

**Issue by zf1234d** [adproqwq/LiteLoaderQQNT-AutoSendMessages#13]
### 需要调整的功能内容

qqnt似乎会在失去焦点后的一段时间内进入休眠，导致计时器只能在固定的唤醒时间运行，通常间隔为一分钟，这导致计时器在休眠时不太可靠。

建议使用时间戳记录运行时间，这样可以计算出具体的计划运行时间，当距离下一次计划运行时间不足1分钟时使用setTimeout控制延迟，确保计时器的可靠性。

这还有一个好处，就是可以支持毫秒级别的定时，虽然间隔时间最短只能到60s，但是60s以上的时间都可以精细设置了。

**Comment by adproqwq** [comment]
单位的精确我会再考虑一下

**Comment by adproqwq** [comment]
[auto_send_messages.zip](https://github.com/user-attachments/files/16776063/auto_send_messages.zip)
这是我做了些修改的包，你用这个看看休眠导致的问题会不会有所改善呢？

**Comment by zf1234d** [comment]
> [auto_send_messages.zip](https://github.com/user-attachments/files/16776063/auto_send_messages.zip) 这是我做了些修改的包，你用这个看看休眠导致的问题会不会有所改善呢？
似乎没有出现休眠问题，但我不能很确信，间隔时间为整数分钟的情况下这个问题不会很明显。

**Comment by adproqwq** [comment]
> 似乎没有出现休眠问题，但我不能很确信，间隔时间为整数分钟的情况下这个问题不会很明显。

我用了多线程去处理定时器，应该会有所改善
