### ISSUE TITLE
[Bug]: “立即触发”有较大概率在第一次成功发送信息后直接失效，X分钟后再次触发完全不能生效。不过发送图片和高级语法都是能用的，就是用一次以后会无法再次触发。

### ISSUE THREAD

**Issue by Miuyou** [adproqwq/LiteLoaderQQNT-AutoSendMessages#14]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-AutoSendMessages/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.15-27597

### LiteLoaderQQNT 版本

1.2.1

### 本插件 版本

1.7.0

### 插件检测更新API插件 版本

1.7.1

### Euphony插件 版本

1.1.1

### 运行环境

Windows

### 重现步骤

如题，再次点击就能触发

### 期望的结果是什么？

希望能解决无法定时长发送的问题，秋梨膏

### 实际的结果是什么？

QAQ

**Comment by Miuyou** [comment]
实测发给自己还是比较稳定的，然后高级语法不知道为什么又挂了，写作AT会按照普通信息输出，At则整个语句无法执行。
或许和我要发送的对象是bot有关？

**Comment by Miuyou** [comment]
反复尝试后在完全一样的设置上跑通了，不过确实是把Euphony更新到最新版了。it just work

**Comment by fatebugs** [comment]
请问一下你艾特bot是怎么写的，我使用这个插件艾特bot无效
