### ISSUE TITLE
[Bug]: 无法使用，放置在插件文件夹后启动加载插件失败

### ISSUE THREAD

**Issue by lxgz12345** [adproqwq/LiteLoaderQQNT-AutoSendMessages#2]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个仅安装本插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-AutoSendMessages/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.9-22961

### LiteLoaderQQNT 版本

1.1.1

### 本插件 版本

1.3.1

### 运行环境

Windows

### 重现步骤

正常放置在插件文件夹内启动NTQQ

### 期望的结果是什么？

正常使用插件

### 实际的结果是什么？

无法使用插件

### 补充说明（可选）

C:\Users\LXGZJ237>"C:\Program Files\Tencent\QQNT\QQ.exe"

C:\Users\LXGZJ237>not mini app.
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
cb8d88941dd9b7d2d0f8851969aebc32a5b89d2eb90df2c34856ae7a9c1ed065
1bbac0cb06564112afa354729c6a1852563703802d1a4456b1ff15520a9986d7
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
e7ad8ee367bf6217eaa26761b31e18584ed2f5aee8ad2198e84761e1f7d984b6
4b350966dc065d1630191443a0dea9be609650684c870c8fe11d3ecd7f55a12d
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-22961
[preload] hotupdate current version: 9.9.9-22961
[preload] install app version: 9.9.9-22961

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-22961\wrapper.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-22961\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: 定时消息 Missing dependencies: euphony
[LiteLoader] Found 1 plugins, start loading plugins.
[preload] register done. launcher.node
[preload] register done. major.node
[auto_send_message] 窗口已创建
[auto_send_message] 窗口信息： BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged]
  },
  _eventsCount: 7,
  devToolsWebContents: [Getter]
}
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
[auto_send_message] 窗口已创建
[auto_send_message] 窗口信息： BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged]
  },
  _eventsCount: 7,
  devToolsWebContents: [Getter]
}
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
cb8d88941dd9b7d2d0f8851969aebc32a5b89d2eb90df2c34856ae7a9c1ed065
1bbac0cb06564112afa354729c6a1852563703802d1a4456b1ff15520a9986d7
error code v2:-8
[auto_send_message] 窗口已创建
[auto_send_message] 窗口信息： BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged]
  },
  _eventsCount: 7,
  devToolsWebContents: [Getter]
}
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10054
00:00:01.702 > [hot update] hotUpdateApi checkHasMultipleQQ false
00:00:01.703 > [hot update] hotUpdateApi start clearOldVersions
00:00:01.704 > [hot update] hotUpdateApi curVersionZipPath is: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-22961.zip false
00:00:01.738 > [hot update] hotUpdateApi checkHasMultipleQQ false
00:00:01.739 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.9-22961
00:00:01.740 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
[auto_send_message] 窗口已创建
[auto_send_message] 窗口信息： BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged]
  },
  _eventsCount: 7,
  devToolsWebContents: [Getter]
}
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
recv failed with error: 10060
[auto_send_message] 窗口已创建
[auto_send_message] 窗口信息： BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged]
  },
  _eventsCount: 7,
  devToolsWebContents: [Getter]
}

**Comment by adproqwq** [comment]
是否安装了Euphony插件？

**Comment by lxgz12345** [comment]
> 是否安装了Euphony插件？

原来要安装那个，安装后已正常，谢谢
