### ISSUE TITLE
[Feat]: 发送消息前添加延迟

### ISSUE THREAD

**Issue by EatHatsuneShallots** [adproqwq/LiteLoaderQQNT-AutoSendMessages#3]
### 需要调整的功能内容

在发送消息前添加延迟，防止被风控甚至被封号

**Comment by adproqwq** [comment]
你指的是群聊和私聊发送消息要错开一定时间吗？

**Comment by EatHatsuneShallots** [comment]
> 你指的是群聊和私聊发送消息要错开一定时间吗？

这个可以，但不是这个意思
我看了一下你的代码，发现消息是（近乎）同时发送的
这非常容易**导致风控，甚至封号！**

**Comment by adproqwq** [comment]
> 消息是（近乎）同时发送的

所以你的意思是每发一条消息需要一段时间的停顿然后再发第二条？

**Comment by EatHatsuneShallots** [comment]
> 所以你的意思是每发一条消息需要一段时间的停顿然后再发第二条？

几秒左右即可，就像 https://github.com/LuckyPray/XAutoDaily 一样
