### ISSUE TITLE
[Bug]: 已经安装，设置不显示

### ISSUE THREAD

**Issue by llkj0001** [adproqwq/LiteLoaderQQNT-AutoSendMessages#5]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-AutoSendMessages/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.11-24815 (64位)

### LiteLoaderQQNT 版本

1.1.1

### 本插件 版本

1.5.1

### 插件检测更新API插件 版本

0

### Euphony插件 版本

0

### 运行环境

Windows

### 重现步骤

设置 => 插件列表查看 => 定时消息 => 安装 => 重启QQ

### 期望的结果是什么？

可以正常加载

### 实际的结果是什么？

无法加载

**Comment by adproqwq** [comment]
是否安装两个依赖的插件
