### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by letterk** [adproqwq/LiteLoaderQQNT-AutoSendMessages#6]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-AutoSendMessages/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.10

### LiteLoaderQQNT 版本

1.1.2

### 本插件 版本

1.5.1

### 插件检测更新API插件 版本

1.5.2

### Euphony插件 版本

1.1.0

### 运行环境

Windows

### 重现步骤

群聊-发送图片

### 期望的结果是什么？

能够正常发送图片

### 实际的结果是什么？

如果选择图片这一操作不是最后进行，后面还修改了别的表单内容，图片地址会被清除

### 补充说明（可选）

前几个版本我就想提issue了，但是你这个条条款款实在是折腾。
可以在插件里设置一个按钮，自动复制环境依赖情况

**Comment by adproqwq** [comment]
> 前几个版本我就想提issue了，但是你这个条条款款实在是折腾。

这几个环境信息在QQ设置页LL菜单里就能全部看见，我自认为不算折腾。而重现步骤等几项，能帮助我更好地理解你提出的bug，并定位问题，这是必要的。其他插件的bug反馈也大差不差，你或许可以提出一个可行的改良方案。
