### ISSUE TITLE
[优化建议]: 白/黑名单模式

### ISSUE THREAD

**Issue by 1807580841** [adproqwq/LiteLoaderQQNT-AutoSendMessages#8]
### 需要调整的功能内容

有些人的群数量太多，一个一个的加太费时间，建议默认定时发送所有群，给那些不发的群加个白名单就行

**Comment by adproqwq** [comment]
后续会推出白名单模式和黑名单模式

**Comment by adproqwq** [comment]
[auto_send_messages.zip](https://github.com/user-attachments/files/16321368/auto_send_messages.zip)
请使用这个版本测试，并反馈效果
